household<-read.table(file="C:/Users/acer/Documents/data analysis coursera/assignment coursera 4/household_power_consumption.txt",header=TRUE,sep=";",colClasses = "character",na.strings = "?")
february<-subset(household,Date %in% c("1/2/2007","2/2/2007"))
png("plot1.png",width = 480,height = 480)
hist(as.numeric(february$Global_active_power),col="red",main="Global Active Power",xlab = "Global Active Power(kilowatts)")
dev.off()
