household<-read.table(file="C:/Users/acer/Documents/data analysis coursera/assignment coursera 4/household_power_consumption.txt",header=TRUE,sep=";",colClasses = "character",na.strings = "?")
february<-subset(household,Date %in% c("1/2/2007","2/2/2007"))
february$Date<-as.Date(february$Date,format="%d/%m/%Y")
datetime<-paste(february$Date,february$Time)
february$datetime<-as.POSIXct(datetime)
with(february,plot(datetime,Sub_metering_1,type="l",xlab="",ylab = "Energy sub meeting"))
lines(february$datetime,february$Sub_metering_2,col="red")
lines(february$datetime,february$Sub_metering_3,col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty = 1,adj = -1,x.intersp = -3,cex = 0.75)
dev.copy(png,"plot3.png",width=480,height=480)
dev.off()
